### ISSUE TITLE
taxonkit reformat erro :panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by hjdong** [shenwei356/taxonkit#14]
**hello,
    I've been having some problems lately when using the latest version:**
```
$ taxonkit list --ids 2,4751,13776,10239 --indent "" -j 8 > bac_fun_arc_vir_taxids.txt
$ taxonkit lineage bac_fun_arc_vir_taxids.txt -o bac_fun_arc_vir_taxids_lineage.txt -j 8
$ time taxonkit reformat -F -f "k__{k}|p__{p}|c__{c}|o__{o}|f__{f}|g__{g}|s__{s}" bac_fun_arc_vir_taxids_lineage.txt -o bac_fun_arc_vir_taxids_lineage_reformat.txt
ids_lineage.txt -o bac_fun_arc_vir_taxids_lineage_reformat.txt

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6f1e49]

goroutine 284259 [running]:
github.com/shenwei356/taxonkit/taxonkit/cmd.glob..func7.1(0xc472103340, 0xae, 0x8, 0x8, 0x9, 0xc4720c4b00, 0x8)
	/home/shenwei/shenwei/script/Go/project/src/github.com/shenwei356/taxonkit/taxonkit/cmd/reformat.go:157 +0x579
github.com/shenwei356/breader.(*BufferedReader).run.func2.1(0xc471116850, 0xc458bea7e0, 0xc4585087c0, 0xc458c98840, 0xc448f384e0, 0xc471116860, 0x108a0, 0xc471f252c0, 0xa, 0xa)
	/home/shenwei/shenwei/script/Go/project/src/github.com/shenwei356/breader/BufferedReader.go:168 +0xef
created by github.com/shenwei356/breader.(*BufferedReader).run.func2
	/home/shenwei/shenwei/script/Go/project/src/github.com/shenwei356/breader/BufferedReader.go:160 +0x245
```
[Uploading bac_fun_arc_vir_taxids.txt…]()

Thanks!

**Comment by shenwei356** [comment]
https://github.com/shenwei356/taxonkit/releases/tag/v0.2.5-dev3

**Comment by shenwei356** [comment]
Note that, option `-F, --fill-miss-rank` is experimental.

**Comment by hjdong** [comment]
谢谢申威！

**Comment by shenwei356** [comment]
It's 沈伟.
