### ISSUE TITLE
An error occurs when running the latest version

### ISSUE THREAD

**Issue by weiguanyue** [shenwei356/taxonkit#81]
### Describe your issue
panic: runtime error: index out of range [5] with length 5

goroutine 18 [running]:
github.com/shenwei356/taxonkit/taxonkit/cmd.stringSplitN({0xc00bf9e0a0?, 0xc000173639?}, {0x93cee8, 0x1}, 0x6?, 0xc000290e40?)
/home/shenwei/go/src/github.com/shenwei356/taxonkit/taxonkit/cmd/util.go:45 +0x1cd
github.com/shenwei356/taxonkit/taxonkit/cmd.getNodes({0xc0001bc420, 0x22}, 0x0)
/home/shenwei/go/src/github.com/shenwei356/taxonkit/taxonkit/cmd/util-basic-data.go:162 +0x1f3
github.com/shenwei356/taxonkit/taxonkit/cmd.loadData.func1()
/home/shenwei/go/src/github.com/shenwei356/taxonkit/taxonkit/cmd/util-basic-data.go:57 +0x134
created by github.com/shenwei356/taxonkit/taxonkit/cmd.loadData
/home/shenwei/go/src/github.com/shenwei356/taxonkit/taxonkit/cmd/util-basic-data.go:53 +0x18d

**Comment by shenwei356** [comment]
Thanks for reporting, but could you please provide more details? Like the command and input data. 

I can't locate the bug with the current panic information. I guess the taxdump files you download or make are incomplete.

**Comment by weiguanyue** [comment]
this is the code:
taxonkit lineage  taxids.txt |head

It's an error no matter how it runs




head taxids.txt 

9606

9913

376619


this is my taxdump



however, view software No problem







At 2023-06-08 18:24:38, "Wei Shen" ***@***.***> wrote:

Thanks for reporting, but could you please provide more details? Like the command and input data.

I can't locate the bug with the current panic information. I guess the taxdump files you download or make are incomplete.

**Comment by shenwei356** [comment]
Cheers! Please let me know, opening another issue,  if you have any problems.
